name: CI and Tests

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Code Quality
    uses: ./.github/workflows/format.yml

  lint:
    name: Code Quality
    needs: format
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    needs: lint
    uses: ./.github/workflows/test.yml

  integration-test:
    name: Integration Test
    needs: lint
    uses: ./.github/workflows/test-integration.yml

  build-image-test:
    name: Test Build Docker Container
    needs: lint
    uses: ./.github/workflows/test-build-image.yml
